version: "3"
services:
  db:
    image: docker.io/library/teastore-db:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"

  webui:
    image: docker.io/library/teastore-webui:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
      OTEL_SERVICE_NAME: "teastore"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_METRICS_EXPORTER: "prometheus"
      OTEL_LOGS_EXPORTER: "otlp"
      CATALINA_OPTS: "$CATALINA_OPTS -javaagent:/opentelemetry-javaagent.jar"
    ports:
      - "8080:8080"
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
      - /:/hostfs
    command: ["--config=/otel-config.yaml"]
    expose:
      - "8889" # Prometheus exporter metrics
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888"
      - "8889"
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    depends_on:
      - db
      - loki
      - prometheus
      - zipkin
      - jaeger
      - grafana

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-admin-api"
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    ports:
      - "3000:3000"
