apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose_default.yaml convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose_default.yaml convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: webui
    spec:
      containers:
        - env:
            - name: CATALINA_OPTS
              value: " -javaagent:/opentelemetry-javaagent.jar"
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: HOST_NAME
              value: webui
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://collector:4317
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_SERVICE_NAME
              value: teastore
            - name: REGISTRY_HOST
              value: registry
          image: andersonalmada/teastore-webui:latest
          name: webui
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
